application: koljaku
version: 1
runtime: python
api_version: 1

handlers:

- url: /favicon\.ico
  static_files: static/favicon.ico
  upload: static/favicon.ico
  mime_type: image/x-icon

- url: /robots\.txt
  static_files: static/robots.txt
  upload: static/robots.txt

- url: /webadmin/.*
  script: $PYTHON_LIB/google/appengine/ext/admin
  login: admin

- url: /tinymce/.* 
  script: $PYTHON_LIB/google/appengine/ext/zipserve
  expiration: "365d"

- url: /icons/.* 
  script: $PYTHON_LIB/google/appengine/ext/zipserve
  expiration: "365d"
  
- url: /static
  static_dir: static/static

- url: .*
  script: main.py
